name: "Issue Game Action"
description: "A GitHub Action that allows you to play games in Issues"
author: "xiaohuohumax"

inputs:
  token:
    required: true
    description: "The Github token for authentication"
    default: ${{ github.token }}
  ttt-issue-title-pattern:
    required: false
    description: "Tic-Tac-Toe game: create room issue title pattern"
    default: "^play\\s+tic[-_]?tac[-_]?toe"
  ttt-label-prefix:
    required: false
    description: "Tic-Tac-Toe game: issue label name prefix"
    default: "game-ttt-room-"

runs:
  using: "node20"
  main: "dist/index.js"
