name: "Issue Game Action"
description: "A GitHub Action that allows you to play games in Issues"
author: "xiaohuohumax"

inputs:
  token:
    required: true
    description: "The Github token for authentication"
    default: ${{ github.token }}
  language:
    required: false
    description: "Language for the game"
    default: "en"
  ttt-issue-title-pattern:
    required: false
    description: "Tic-Tac-Toe game: create room issue title pattern"
    default: "^play\\s+tic[-_]?tac[-_]?toe"
  ttt-label:
    required: false
    description: "Tic-Tac-Toe game: issue label name"
    default: "game-ttt-room"
  ttt-extra-labels:
    required: false
    description: "Tic-Tac-Toe game: extra issue labels"
    default: |
      game-ttt
  ttt-room-title:
    required: false
    description: "Tic-Tac-Toe game: room title"
    # {name} game name: Tic-Tac-Toe
    # {state} game state: init | waiting | playing | end
    # {vs} player name: player1_name vs player2_name
    # {creator} room creator name: player_name
    # {next} next player name: player_name
    # {winner} winner name: player_name
    # {result} game result: player wins | tie
    default: "♟|{name}| {state}| {vs}| {result}"

runs:
  using: "node20"
  main: "dist/index.js"
